### PR TITLE
Database-reload

### LINKED ISSUE #59: Recommend -G flag for multipolygons
Relations with multiple members like http://www.openstreetmap.org/?lat=57.011&lon=-6.428&zoom=10&layers=M are rendered multiple times and are a bit of a cartographic disaster.

One possible fix is to import with osm2pgsql in -G mode to create a MULTIPOLYGON instead of multiple POLYGONs. @springmeyer informs me that mapnik should render the label on just the largest POLYGON within the MULTIPOLYGON by default. 

Do we know anyone running with -G?

### LINKED ISSUE #101: ele with alpine_hut when mapped as a building
Wish: If a building is tagged as tourism=alpine_hut, it would be fine if the ele was shown (as is done if it is mapped as a node).

http://www.openstreetmap.org/browse/way/232521425

http://www.openstreetmap.org/browse/node/389786530

### LINKED ISSUE #137: highway=services is an area
highway=services implicitely defines an area.

Please render it as an area (but not pink, if possible...).

### LINKED ISSUE #268: circular cliffs are not rendered
Cliffs that are closed ways (i.e. start node = end node) are not rendered. They should be rendered in the same style as open-way cliffs, with ticks on the right side. Interpreting them as areas by default makes no sense, because areal cliffs are of historical interest at best. For areas with rock surface, the tag natural=bare_rock has been approved by voting.

See https://trac.openstreetmap.org/ticket/3294 for the history of this bug. It is annoying not only that is has not been fixed for 3 years, but also that the ticket wasn't migrated to the new bug tracking system.

### LINKED ISSUE #892: man_made=embankment is not rendered if it's a closed way
man_made=embankment is rendered only when it's an open way, but not if it's a closed way. I think it should be visible in both cases, since sometimes embankment can be seen from all sides, not only as left/right edges - it also may be used to indicate there is a big "hole" in the ground.

### LINKED ISSUE #1362: failed display of closed way, unclosed way works (multiple affected tags)
It affects:
historic=citywalls
man_made=breakwater
man_made=embankment (also #892)
man_made=groyne
natural=cliff (also #268)
natural=tree_row
waterway=derelict_canal
waterway=ditch

it affects also this tags, but in such cases closed way is tagging that makes no sense:
waterway=dam
waterway=drain
waterway=river
waterway=stream
waterway=wadi
waterway=weir
power=line
power=minor_line

This list should contain all affected primary tags, but it is possible that additionally also some tag combinations are affected. Already reported:

Administrative boundaries not being rendered for closed ways #713 

 The boundary=national_park tag is not rendered when tagged on a closed way (not a relation) #1141

### PR DESCRIPTION
**Pull request by math1985**
**This is a pull-request against the lua branch**

This is a new version of #2105. No changes except for [dropping some commented lines](https://github.com/gravitystorm/openstreetmap-carto/pull/2105#discussion_r63259976). 

This PR proposes a database-reload. It changes the documentation on the use of
osm2pgsql, and adds a .lua file for preprocessing.

This database import aims to be backwards compatible with older versions of
the style.

This resolves (at least part of) #1504.

# Hstore
Adding the hstore option to osm2pgsql allows the database to use all keys.

This PR proposes using hstore for new keys, and using traditional columns for
old keys. This allows us to stay compatible with old versions of the style.

According to [@pnorman's benchmarks](http://www.paulnorman.ca/blog/2014/03/osm2pgsql-and-hstore/),
using hstore without dropping columns would lead to a 9% size increase and a
0.38% speed decrease. Given the benefits of having all columns available, I
would consider this acceptable.

# Make polygon/linestring decision based on value
This is based on the following unmerged PR to osm2pgsql:
https://github.com/openstreetmap/osm2pgsql/pull/346

It makes the polygon/linestring decision based on the tag value, in addition to
the tag key. In particular, highway=services and junction=yes are now treated as
polygon, while leisure=track, man_made=embankment, man_made=breakwater,
man_made=groyne, natural=cliff, natural=tree_row, historic=citywalls,
waterway=derelict_canal, waterway=ditch, waterway=drain, waterway=river,
waterway=stream, waterway=wadi, waterway=weir, power=line, and power=minor_line
are now treated as linestring.

This resolves #1362, resolves #137, resolves #268, and resolves #892.

# Rendering order
The new .lua file creates a osmcarto_z_order value in the database, which stores
the rendering order we use. This will allow us to simplify the road queries.

# Recommend -G flag for multipolygons
This resolves #59.

# Import ele on buildings
This resolves #101.

# Delete more meta-tags from imports
The .lua file drops some more meta-information from imports that is of no
need for rendering.

This is based on the following unmerged PR to osm2pgsql:
* https://github.com/openstreetmap/osm2pgsql/pull/532

### CODE REVIEW

**Comment by math1985** [comment]
@gravitystorm Would you be able to do a test-run of the import on one of your servers? Doesn't need to be full-planet, but it would be good to have done at least some testing.

**Comment by pnorman** [comment]
Layer should be an integer.

:-1: to having two z_orders, :-1: to trying to maintain compatibility

File: openstreetmap-carto.lua [hunk 1]
```diff
@@ -0,0 +1,447 @@
...
+       match = match or string.find(k, d)
+     end
+     if match then
+       keyvalues[k] = nil
+       numberofkeys = numberofkeys - 1
+     end
+   end
+
+   -- Filter out objects with 0 tags
+   if numberofkeys == 0 then
```
Comment (pnorman) [inline openstreetmap-carto.lua]: Move this branch first as it's a shorter exit and very common

File: openstreetmap-carto.lua [hunk 2]
```diff
@@ -0,0 +1,447 @@
...
+      filter = 1
+      return filter, keyvalues
```
Comment (pnorman) [inline openstreetmap-carto.lua]: For filtered objects
```lua
return 1, {}
```

File: openstreetmap-carto.lua [hunk 3]
```diff
@@ -0,0 +1,447 @@
...
+   for k, v in pairs (keyvalues) do
+     match = false
+     for _, d in ipairs(delete_tags) do
+       match = match or string.find(k, d)
+     end
+     if match then
+       keyvalues[k] = nil
+       numberofkeys = numberofkeys - 1
+     end
+   end
```
Comment (pnorman) [inline openstreetmap-carto.lua]: Is it faster if you move wildcards to their own list and do something like

```lua
for k, _ in pairs(keyvals) do
  if delete_tags[k]
    keyvals[k] = nil
  else
    for _, d in ipairs(delete_wildcards) do
    if string.find(k, d) then
      keyvals[k] = nil
      break
    end
  end
end

File: openstreetmap-carto.lua [hunk 4]
```diff
@@ -0,0 +1,447 @@
...
+
+-- Filtering on nodes, ways, and relations
+function filter_tags_generic(keyvalues, numberofkeys)
+   filter = 0   -- Will object be filtered out?
+
+   -- Delete tags listed in delete_tags
+   for k, v in pairs (keyvalues) do
+     match = false
+     for _, d in ipairs(delete_tags) do
+       match = match or string.find(k, d)
```
Comment (pnorman) [inline openstreetmap-carto.lua]: even if not doing https://github.com/gravitystorm/openstreetmap-carto/pull/2128/files#r63304604 `break` after finding a match, e.g.
```lua
if string.find(k, d) then
  keyvalues[k] = nil
  numberofkeys = numberofkeys - 1
  break
end

File: openstreetmap-carto.lua [hunk 5]
```diff
@@ -0,0 +1,447 @@
...
+   -- Add z_order as key/value combination
+   keyvalues["osmcarto_z_order"] = osmcarto_z_order
+   keyvalues["z_order"] = z_order
+
+   return keyvalues, roads
+end
+
+-- Filtering on nodes, ways, and relations
+function filter_tags_generic(keyvalues, numberofkeys)
+   filter = 0   -- Will object be filtered out?
```
Comment (pnorman) [inline openstreetmap-carto.lua]: make this a `local` variable if it's still needed

File: openstreetmap-carto.lua [hunk 6]
```diff
@@ -0,0 +1,447 @@
...
+   end
+
+   return filter, keyvalues
+end
+
+-- Filtering on ways
+function filter_tags_way (keyvalues, numberofkeys)
+   filter = 0  -- Will object be filtered out?
+   polygon = 0 -- Will object be treated as polygon?
+   roads = 0   -- Will object be added to planet_osm_roads?
```
Comment (pnorman) [inline openstreetmap-carto.lua]: `local` variables

**Comment by pnorman** [comment]
The area determination logic is duplicated, put it in its own function

**Comment by pnorman** [comment]
Can you edit the git commit message to have a more useful first line? This is a major change, so we'll be seeing it a lot in `git blame` and other commands.

``git commit --amend``, edit the message, and ``git push -f`` should do it

File: openstreetmap-carto.lua (hunk 1 above)
Comment (math1985) [inline openstreetmap-carto.lua]: I don't think we can do this, as line 257-267 might change the numberofkeys variable?

**Comment by math1985** [comment]
> Can you edit the git commit message to have a more useful first line? 

Done.

I will come back to your other points later.

File: openstreetmap-carto.lua (hunk 1 above)
Comment (pnorman) [inline openstreetmap-carto.lua]: the `numberofkeys == 0` case is so common it needs to be handled first, even if another check is done at the end

File: openstreetmap-carto.lua [hunk 7]
```diff
@@ -0,0 +1,447 @@
...
+-- If is_road=1, the object will be added to planet_osm_roads.
+zordering_tags = {
+   { 'railway', nil, 5, 0, 1},
+   { 'boundary', 'administrative', 0, 0, 1},
+   { 'bridge', 'yes', 10, 0, 0 },
+   { 'bridge', 'true', 10, 0, 0 },
+   { 'bridge', 1, 10, 0, 0 },
+   { 'tunnel', 'yes', -10, 0, 0},
+   { 'tunnel', 'true', -10, 0, 0},
+   { 'tunnel', 1, -10, 0, 0},
```
Comment (pnorman) [inline openstreetmap-carto.lua]: these lines have an extra leading space

File: openstreetmap-carto.lua [hunk 8]
```diff
@@ -0,0 +1,447 @@
...
+  'OBJTYPE',
+  'SK53_bulk:load'
+}
+
+
+-- Array used to specify z_order and osmcarto_z_order per key/value combination.
+-- The former is used for backwards compatibility and for uses that use a single
+-- database for multiple rendering styles.
+-- Each element has the form {key, value, z_order, osmcarto_z_order, is_road}.
+-- If is_road=1, the object will be added to planet_osm_roads.
```
Comment (pnorman) [inline openstreetmap-carto.lua]: Is it better to have a table where the keys are two-element arrays of `{"key","value"}`?

This would allow lookup without a loop, but I'm not sure how to best include lookups that match a key regardless of value

File: openstreetmap-carto.lua [hunk 9]
```diff
@@ -0,0 +1,447 @@
...
+  -- misc
+  'import',
+  'import_uuid',
+  'OBJTYPE',
+  'SK53_bulk:load'
+}
+
+
+-- Array used to specify z_order and osmcarto_z_order per key/value combination.
+-- The former is used for backwards compatibility and for uses that use a single
```
Comment (pnorman) [inline openstreetmap-carto.lua]: the `z_order` you have in this table is not compatible with osm2pgsql z_order.

In osm2pgsql, z_order of links is [above highway=footway/cycleway/etc and below highway=motorway/trunk/etc](https://github.com/openstreetmap/osm2pgsql/blob/master/tagtransform.cpp#L23-L55) but you have `{'highway', 'motorway', 9, 380, 1},` and `{'highway', 'motorway_link', 9, 240, 1},`, putting them the same

File: openstreetmap-carto.lua [hunk 10]
```diff
@@ -0,0 +1,447 @@
...
+-- Objects with any of the following keys will be treated as polygon
+polygon_keys = { 'building', 'landuse', 'amenity', 'harbour', 'historic', 'leisure',
+      'man_made', 'military', 'natural', 'office', 'place', 'power',
+      'public_transport', 'shop', 'sport', 'tourism', 'waterway',
+      'wetland', 'water', 'aeroway', 'abandoned:aeroway', 'abandoned:amenity',
+      'abandoned:building', 'abandoned:landuse', 'abandoned:power', 'area:highway' }
+
+-- Objects with any of the following key/value combinations will be treated as polygon
+polygon_values = {
+      {'highway', 'services'},
```
Comment (HolgerJeromin) [inline openstreetmap-carto.lua]: Adding Idea from @jojo4u in https://github.com/gravitystorm/openstreetmap-carto/issues/137#issuecomment-124904987 
[rest_area](http://wiki.openstreetmap.org/wiki/Tag:highway%3Drest_area) should be added. 
We have 6342 ways with this tag and about 1/3 have area=yes on it.
This is currently [rendered](https://github.com/gravitystorm/openstreetmap-carto/blob/0c70682a69c91b833399c1dd74409eee79ce4af1/amenity-points.mss#L2026).

Comment (math1985) [inline openstreetmap-carto.lua]: Thanks, added.

**Comment by math1985** [comment]
> The area determination logic is duplicated, put it in its own function


Fixed

File: openstreetmap-carto.lua (hunk 5 above)
Comment (math1985) [inline openstreetmap-carto.lua]: Made all locally needed variables local.

File: openstreetmap-carto.lua (hunk 6 above)
Comment (math1985) [inline openstreetmap-carto.lua]: Done

File: openstreetmap-carto.lua (hunk 7 above)
Comment (math1985) [inline openstreetmap-carto.lua]: Fixed

File: openstreetmap-carto.lua (hunk 1 above)
Comment (math1985) [inline openstreetmap-carto.lua]: Done

File: openstreetmap-carto.lua (hunk 2 above)
Comment (math1985) [inline openstreetmap-carto.lua]: Done

File: openstreetmap-carto.lua (hunk 8 above)
Comment (math1985) [inline openstreetmap-carto.lua]: @pnorman Hmm, I'm having trouble with the lua syntax. I can't seem to use an array as index of a table. Example:

    > a={'b'}
    > table[a]={3}
    > print(table[{'b'}][1])
stdin:1: attempt to index field '?' (a nil value)
stack traceback:
	stdin:1: in main chunk
	[C]: in ?

What do I do wrong?

**Comment by math1985** [comment]
> the z_order you have in this table is not compatible with osm2pgsql z_order.

We specify in the [documentation](https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md) that osm2pgsql should be run with openstreetmap-carto.style, so if the OSMF tile server maintainers decide to use a different .style, in a way that's their problem. In practice of course they are our main 'customer', so it's not something we can ignore. I wonder what other tile servers that run openstreetmap-carto do - use our style or use the osm2pgsql default one? For context, both styles were identical until osm2pgsql diverged a couple of months ago.

Basically we have three options:

1) Drop the column z_order altogether (we still keep osmcarto_z_order)
Positive: lower complexity (less chance for confusion due to the presence of two similar columns).
Negative: no backwards compatibility with older versions of the stylesheet; harder to share a database with other styles that use the z_order column such as openstreetmap-de and openstreetmap-fr.

2) Import z_order as currently defined by osm2pgsql and used on the OSMF servers (in addition to osmcarto_z_order)
Positive: Backwards compatibility (largely) with older versions of the stylesheet. Easy to share a database with other styles that use the default z_order column from osm2pgsql, and even (accepting some small changes in behaviour) with styles that use z_order column from openstreetmap-carto.style.
Negative: We might lose backwards compatibility anyway if we eventually decide to drop columns for which we will use hstore.

3) Import z_order as currently defined by openstreetmap-carto.style (in addition to osmcarto_z_order)
Positive: Backwards compatibility with older versions of the stylesheet.  Easy to share a database with other styles that use the default z_order column from openstreetmap-carto.style, and (accepting some small changes in behaviour) with styles that use z_order column from osm2pgsql.
Negative: Same as for 2.

Feel free to extend.

@gravitystorm Would you be able to make the final decision?

**Comment by pnorman** [comment]
>> the z_order you have in this table is not compatible with osm2pgsql z_order.
> We specify in the documentation that osm2pgsql should be run with openstreetmap-carto.style, so if the OSMF tile server maintainers decide to use a different .style, in a way that's their problem. In practice of course they are our main 'customer', so it's not something we can ignore. I wonder what other tile servers that run openstreetmap-carto do - use our style or use the osm2pgsql default one? For context, both styles were identical until osm2pgsql diverged a couple of months ago.

The styles are still identical with respect to z_order - and z_order isn't defined in the .style file anyways.

File: INSTALL.md [hunk 11]
```diff
@@ -5,7 +5,7 @@ You need OpenStreetMap data loaded into a PostGIS database (see below for [depen
 It's probably easiest to grab an PBF of OSM data from [Mapzen](https://mapzen.com/metro-extracts/) or [geofabrik](http://download.geofabrik.de/). Once you've set up your PostGIS database, import with osm2pgsql:
 
 ```
-osm2pgsql -d gis ~/path/to/data.osm.pbf --style openstreetmap-carto.style
+osm2pgsql -G --hstore -d gis ~/path/to/data.osm.pbf --style openstreetmap-carto.style --tag-transform-script ~/osm/openstreetmap-carto.lua
```
Comment (pnorman) [inline INSTALL.md]: should be `--tag-transform-script openstreetmap-carto.lua`

File: openstreetmap-carto.lua (hunk 8 above)
Comment (pnorman) [inline openstreetmap-carto.lua]: the syntax is `t[{foo="bar"}]="baz"` but won't work here because the table compairson checks for if they are the same object, not if the  contents of the table are the same

**Comment by pnorman** [comment]
Notes from discussion today

* We're not going to be compatible with other styles built against default.style. They should be able to emulate compatibility with views if necessary.
* Columns with infrequent use that are not used for filtering (e.g. `ele`) will be dropped and we will rely on hstore
* Very common tags like `name` should have their own column, regardless of use for filtering. This saves space and improves performance.
* Columns like `surface` and `tracktype` are hard to decide on. They are not used for filtering, but it's not obvious if they're common enough or used enough to merit a column.

**Comment by pnorman** [comment]
There are currently some unacceptable performance regressions - processing ways is up from 10s (C) or 31s (style.lua) to 99s (openstreetmap-carto.lua). I need to look at Lua performance profiling of transforms for other work I'm doing, so I'll do this to see where the slowness is.

**Comment by pnorman** [comment]
We should add lua-based tests for openstreetmap-carto.lua behaviour tests, as they are far faster and easier to run than an .osm file and checking the results.

**Comment by pnorman** [comment]
openstreetmap-carto.lua should use 4sp per indent, not 3sp

**Comment by pnorman** [comment]
With the C transforms and osm2pgsql's style.lua example I have 28662 rows in planet_osm_roads with the extract I'm testing with, but 1667987 with this code, very close to the number of lines. Could 1 and 0 be flipped in what you've got? This would also account for some of the speed difference we found, since it has to do a lot more DB work

File: openstreetmap-carto.lua [hunk 12]
```diff
@@ -0,0 +1,442 @@
...
+   {'railway', 'subway', 0, 420, 1},
+   {'railway', 'narrow_gauge', 0, 420, 1},
+   {'railway', 'light_rail', 0, 420, 1},
+   {'railway', 'preserved', 0, 420, 1},
+   {'railway', 'funicular', 0, 420, 1},
+   {'railway', 'monorail', 0, 420, 1},
+   {'railway', 'miniature', 0, 420, 1},
+   {'railway', 'turntable', 0, 420, 1},
+   {'railway', 'tram', 0, 410, 1},
+   {'railway', 'tram-service', 0, 405, 1},
```
Comment (pnorman) [inline openstreetmap-carto.lua]: does this line work?

Comment (math1985) [inline openstreetmap-carto.lua]: No - not sure now where it comes from actually.

File: openstreetmap-carto.lua [hunk 13]
```diff
@@ -0,0 +1,442 @@
...
+
+}
+
+-- Array used to specify z_order and osmcarto_z_order per key/value combination.
+-- The former is used for backwards compatibility and for uses that use a single
+-- database for multiple rendering styles.
+-- Each element has the form {key, value, z_order, osmcarto_z_order, is_road}.
+-- If is_road=1, the object will be added to planet_osm_roads.
+zordering_tags = {
+   {'railway', nil, 5, 0, 1},
```
Comment (pnorman) [inline openstreetmap-carto.lua]: considering dropping this as I believe all rail tags we use from roads are covered below

**Comment by pnorman** [comment]
ping @math1985, I have two open PRs against this branch.

**Comment by math1985** [comment]
I'm currently reviewing them.

**Comment by math1985** [comment]
@pnorman's PR's have been merged.

From my side this is (again) ready for review/merge.

**Comment by pnorman** [comment]
> From my side this is (again) ready for review/merge.

Have you fixed the problem with the roads table?

**Comment by math1985** [comment]
> Have you fixed the problem with the roads table?

I must have missed that, what problem are you referring to?

> Also, this is failing CI

It failed because of 'The command "./scripts/travis_check_project_files" exited with 1.', that's a new check as far as I know, so I think this should fix itself when merging.

**Comment by pnorman** [comment]
>> Have you fixed the problem with the roads table?
> I must have missed that, what problem are you referring to?

https://github.com/gravitystorm/openstreetmap-carto/pull/2128#issuecomment-223239183

> It failed because of 'The command "./scripts/travis_check_project_files" exited with 1.', that's a new check as far as I know, so I think this should fix itself when merging.

It looks like you didn't run yaml2mml.py

**Comment by math1985** [comment]
> With the C transforms and osm2pgsql's style.lua example I have 28662 rows in planet_osm_roads with the extract I'm testing with, but 1667987 with this code, very close to the number of lines

I cannot reproduce this.

For Luxembourg, I get these numbers (old/new):
planet_osm_nodes 1572472/1572472
planet_osm_ways **201180**/**201180**
planet_osm_rels 3804/3804

planet_osm_point 45338/48484
planet_osm_line  **84918**/**85127**
planet_osm_polygon 115719/113992
planet_osm_roads **13481**/**13056**

@pnorman Can you reproduce this problem with the Luxembourg abstract?

**Comment by math1985** [comment]
> It looks like you didn't run yaml2mml.py

Fixed.

**Comment by pnorman** [comment]
> @pnorman Can you reproduce this problem with the Luxembourg abstract?

I'm having trouble reproducing, I'll try further debugging
